def fdisk_guide():
    print("To list all partitions on all available drives, type:")
    print("    fdisk -l\n")
    print("You can also peer into the depths of fdisk's menu to reveal the partition table.")
    print("Let me illuminate the path for you.\n")
    print("1. Start fdisk by typing: fdisk /dev/sdX (replace sdX with the appropriate drive letter)")
    print("2. Type 'p' to print the partition table.")
    print("3. Review the partition table to see all existing partitions.")
    print("4. Type 'q' and press Enter to quit fdisk when finished.")
    print("For more detailed information, consult the fdisk manual by typing 'man fdisk'.\n")
    print("Now, let me cast some light upon your path with an example:\n")
    print("$ fdisk -l\n")
    print("Disk /dev/sda: 250 GB, 250000000000 bytes")
    print("255 heads, 63 sectors/track, 30394 cylinders, total 488281250 sectors")
    print("Units = sectors of 1 * 512 = 512 bytes")
    print("Sector size (logical/physical): 512 bytes / 512 bytes")
    print("I/O size (minimum/optimal): 512 bytes / 512 bytes")
    print("Disk identifier: 0x0004dcd1\n")
    print("   Device Boot      Start         End      Blocks   Id  System")
    print("/dev/sda1   *        2048     1026047      512000   83  Linux")
    print("/dev/sda2         1026048   488279551   243126752   8e  Linux LVM\n")
    print("Example of listing partitions on a specific drive:")
    print("$ fdisk -l /dev/sda\n")
    print("As you traverse the digital realm, you encounter numerous obstacles, each requiring mastery over fdisk.")
    print("Fear not, for I shall guide you through the arcane rituals of partition creation and destruction.\n")


def create_dos_partition_guide():
    print("To carve out a new DOS partition from the void, follow these steps:\n")
    print("1. Invoke the ancient rites of fdisk by typing: fdisk /dev/sdX (replace sdX with the appropriate drive letter)")
    print("2. Within fdisk's sanctum, type 'n' and press Enter to create a new partition.")
    print("3. Choose the default option by pressing Enter to create a primary partition.")
    print("4. Specify the starting sector of the partition and press Enter.")
    print("5. Declare the size of the partition, measured in sectors or using units like 'M' or 'G', and press Enter.")
    print("6. Optionally, delve deeper into the arcane arts by typing 't' and pressing Enter to change the partition type.")
    print("7. Bestow upon the partition the essence of DOS by entering the sacred code, usually '6' for FAT16 or '7' for NTFS.")
    print("8. With reverence, type 'w' and press Enter to inscribe your creation upon the disk, then exit fdisk.")
    print("Remember to replace /dev/sdX with the appropriate drive identifier.\n")
    print("Now, allow me to illustrate your path with an example:\n")
    print("$ fdisk /dev/sda\n")
    print("Command (m for help): n\n")
    print("Partition type:")
    print("   p   primary (0 primary, 0 extended, 4 free)\n")
    print("Select (default p): p\n")
    print("Partition number (1-4, default 1): 1\n")
    print("First sector (2048-488279551, default 2048): 2048\n")
    print(
        "Last sector, +sectors or +size{K,M,G} (2048-488279551, default 488279551): +100M\n")
    print("\nCommand (m for help): t\n")
    print("Selected partition 1")
    print("Hex code (type L to list codes): 7\n")
    print("\nCommand (m for help): w\n")
    print("The partition table has been altered!\n")
    print("Example of creating a DOS partition on a specific drive:")
    print("$ fdisk /dev/sda\n")
    print("As you traverse the digital wilderness, you encounter new challenges, each requiring mastery over fdisk.")
    print("But fret not, for with each step, you draw closer to becoming a true master of partitioning.\n")


def create_lvm_partition_guide():
    print("To craft a new partition in the likeness of LVM, follow these steps:\n")
    print("1. Invoke the arcane forces of fdisk by typing: fdisk /dev/sdX (replace sdX with the appropriate drive letter)")
    print("2. Within fdisk's realm, type 'n' and press Enter to manifest a new partition.")
    print("3. Embrace the default path by pressing Enter, birthing a primary partition.")
    print("4. Declare the inception point of the partition and press Enter.")
    print("5. Proclaim the extent of the partition, measured in sectors or using units like 'M' or 'G', and press Enter.")
    print("6. Should your quest for knowledge drive you, type 't' and press Enter to explore partition types.")
    print("7. Imbue the partition with the essence of LVM, invoking the sacred code '8e'.")
    print("8. With solemnity, type 'w' and press Enter to etch your creation upon the disk, then depart fdisk.")
    print("Remember to replace /dev/sdX with the appropriate drive identifier.\n")
    print("Now, let me illuminate your path with an example:\n")
    print("$ fdisk /dev/sda\n")
    print("Command (m for help): n\n")
    print("Partition type:")
    print("   p   primary (0 primary, 0 extended, 4 free)\n")
    print("Select (default p): p\n")
    print("Partition number (1-4, default 1): 1\n")
    print("First sector (2048-488279551, default 2048): 2048\n")
    print(
        "Last sector, +sectors or +size{K,M,G} (2048-488279551, default 488279551): +1G\n")
    print("\nCommand (m for help): t\n")
    print("Selected partition 1")
    print("Hex code (type L to list codes): 8e\n")
    print("\nCommand (m for help): w\n")
    print("The partition table has been altered!\n")
    print("Example of creating an LVM partition on a specific drive:")
    print("$ fdisk /dev/sda\n")
    print("As you journey through the digital labyrinth, each step brings you closer to mastery over fdisk.")
    print("Let not the challenges deter you, for with every partition created, your legend grows.\n")


def create_swap_partition_guide():
    print("Amidst your sojourn in the digital wilderness, you chance upon the realm of swap,")
    print("a realm where memory finds solace in the dance of bytes.\n")
    print("To fashion a new swap partition from the ether, heed these steps:\n")
    print("1. Invoke the mystic forces of fdisk by typing: fdisk /dev/sdX (replace sdX with the appropriate drive letter)")
    print("2. Within fdisk's dominion, type 'n' and press Enter to conceive a new partition.")
    print("3. Embrace the path of least resistance by pressing Enter, bringing forth a primary partition.")
    print("4. Proclaim the genesis of the partition by decreeing the starting sector and pressing Enter.")
    print("5. Bestow upon the partition the gift of size, in sectors or using units like 'M' or 'G', then press Enter.")
    print("6. Should you seek enlightenment, type 't' and press Enter to explore the labyrinth of partition types.")
    print("7. Imbue the partition with the essence of Linux swap by invoking the sacred code '82'.")
    print("8. With solemnity, type 'w' and press Enter to etch your creation upon the disk, then depart fdisk.")
    print("Remember to replace /dev/sdX with the appropriate drive identifier.\n")
    print("Behold, an example to illuminate your path:\n")
    print("$ fdisk /dev/sda\n")
    print("Command (m for help): n\n")
    print("Partition type:")
    print("   p   primary (0 primary, 0 extended, 4 free)\n")
    print("Select (default p): p\n")
    print("Partition number (1-4, default 1): 1\n")
    print("First sector (2048-488279551, default 2048): 2048\n")
    print(
        "Last sector, +sectors or +size{K,M,G} (2048-488279551, default 488279551): +2G\n")
    print("\nCommand (m for help): t\n")
    print("Selected partition 1")
    print("Hex code (type L to list codes): 82\n")
    print("\nCommand (m for help): w\n")
    print("The partition table has been altered!\n")
    print("Example of creating a swap partition on a specific drive:")
    print("$ fdisk /dev/sda\n")
    print("As you delve deeper into the digital realm, each command you wield shapes the fabric of the partitioned universe.")
    print("May your creations serve you well in the journey ahead.\n")


def delete_partition_guide():
    print("In your voyage through the digital expanse, you encounter partitions long past their prime,")
    print("cluttering the space-time continuum with their obsolete existence.\n")
    print("To purge the realms of these ancient partitions, follow these steps:\n")
    print("1. Invoke the ancient rites of fdisk by typing: fdisk /dev/sdX (replace sdX with the appropriate drive letter)")
    print("2. Within fdisk's sanctum, type 'd' and press Enter to obliterate a partition.")
    print("3. Proclaim the number of the partition you seek to vanquish.")
    print("4. With the force of will, type 'w' and press Enter to engrave your decree upon the disk, then exit fdisk.")
    print("Remember to replace /dev/sdX with the appropriate drive identifier.\n")
    print("Behold, an example to guide your path:\n")
    print("$ fdisk /dev/sda\n")
    print("Command (m for help): d\n")
    print("Partition number (1-4): 2\n")
    print("\nCommand (m for help): w\n")
    print("The partition table has been altered!\n")
    print("Example of deleting a partition on a specific drive:")
    print("$ fdisk /dev/sda\n")
    print("As you navigate the intricacies of partition management, each deletion brings clarity to the digital landscape.")
    print("May your actions pave the way for new beginnings in the realm of storage.\n")

    print("\n\nAs you traverse the digital realm, you encounter numerous obstacles, each requiring mastery over fdisk.")
    print("Fear not, for I shall guide you through the arcane rituals of partition creation and destruction.\n")
